
name: Github action for your deployment

on:
    push:
      branches: [main]

jobs:
    build:

        runs-on: ubuntu-latest

        strategy:
            matrix: 
                node-version: [16.14.2]

        steps:
        - uses: actions/checkout@v3
        - name: Using node ${matrix.node-version}
          uses: actions/setup-node@v2
          with: 
            node-version: ${matrix.node-version}
            cache: 'npm'
        - run: npm install
        - name: Creating a Dockerfile
          run: |
            echo "
            FROM node
            WORKDIR /app
            COPY package*.json .
            RUN npm install
            COPY . .
            EXPOSE 8000
            CMD ["node", "server"]
            " > Dockerfile
        - name: Installing patr-cli
          run: snap install patr -y

        - name: Build image from Dockerfile and push to patr-registry
          run: |
            docker login -u rakshith-ravi -p ${REGISTRY_PASSWORD} registry.patr.cloud
            docker build . -t rakshith-ravi/deployment
            docker tag rakshith-ravi/deployment registry.patr.cloud/personal-workspace-a45b1cb6f48b4437ae8543a33fbf7786/test:latest 
            docker push registry.patr.cloud/personal-workspace-a45b1cb6f48b4437ae8543a33fbf7786/test:latest
